--CREATE DATABASE exclucvDb_10_Dev
--USE exclucvDb_10_Dev

DROP TABLE IF EXISTS [User]
DROP TABLE IF EXISTS UserTracking
DROP TABLE IF EXISTS Contacts
DROP TABLE IF EXISTS Template
DROP TABLE IF EXISTS Skill
DROP TABLE IF EXISTS Education
DROP TABLE IF EXISTS Experience

CREATE TABLE [User] (
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	Email NVARCHAR(128) NOT NULL,
	[Password] NVARCHAR(512) NOT NULL,
	ProfileImage NVARCHAR(256) DEFAULT 'Resources/Default/default.jpg',
)

CREATE TABLE UserTracking (
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	LastLogin DATETIME,
	RegisterDate DATETIME,
	UserId UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT FK_UserUserTracking FOREIGN KEY (UserId)
	REFERENCES [User](Id)
)

CREATE TABLE Contacts (
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	FirstName NVARCHAR(64) NOT NULL,
	MiddleName NVARCHAR(64),
	LastName NVARCHAR(64) NOT NULL,
	MobileNumber NVARCHAR(64) NOT NULL,
	Country NVARCHAR(64) NOT NULL,
	Town NVARCHAR(64) NOT NULL,
	PostalCode NVARCHAR(16) NOT NULL,
	UserId UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT FK_UserContacts FOREIGN KEY (UserId)
	REFERENCES [User](Id)
)

CREATE TABLE Template (
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	Summary NVARCHAR(1024),
	UserId UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT FK_UserTemplate FOREIGN KEY (UserId)
	REFERENCES [User](Id)
)

CREATE TABLE Skill (
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	[Name] NVARCHAR(128) NOT NULL,
	TemplateId UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT FK_TemplateSkill FOREIGN KEY (TemplateId)
	REFERENCES Template(Id)
)

CREATE TABLE Education (
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	Institution NVARCHAR(128) NOT NULL,
	Class NVARCHAR(64) NOT NULL,
	Degree NVARCHAR(32) NOT NULL,
	StartDate DATE NOT NULL,
	GraduationDate DATE,
	TemplateId UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT FK_TemplateEducation FOREIGN KEY (TemplateId)
	REFERENCES Template(Id)
)

CREATE TABLE Experience (
	Id UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
	Company NVARCHAR(128) NOT NULL,
	Position NVARCHAR(64) NOT NULL,
	StartDate DATE NOT NULL,
	LeaveDate DATE,
	Responsibility NVARCHAR(256),
	TemplateId UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT FK_TemplateExperience FOREIGN KEY (TemplateId)
	REFERENCES Template(Id)
)